### ISSUE TITLE
Add GitHub Raffle at Intro to Codespaces - Leave a comment to enter

### ISSUE THREAD

**Issue by AndreaGriffiths11** [gittogethers/intro-codespaces#3]
🏆 The prize will be drawn at the end of the stream

A couple of T&C's:

- Entry into this raffle will NOT constitute your consent to be contacted for anything else
- We will not be adding you to our marketing database (but if you want to subscribe to our newsletter, [you can do so here](https://resources.github.com/newsletter/))
- The raffle prize cannot be swapped or changed,
- The winner of the prize MUST be present when we draw a winner, otherwise we will redraw!
- Good luck!

**Comment by mona** [comment]
🍀

**Comment by icebeam7** [comment]
Good luck everyone!

**Comment by aggierunner** [comment]
Hola amigos

**Comment by adnamaric** [comment]
hello

**Comment by burhankhatri** [comment]
hiiiii

**Comment by westerdaled** [comment]
Can we use codespaces with Azure DevOps ?

**Comment by marcel-paalvast** [comment]
Hey there :)

**Comment by Kmtengo** [comment]
Sup

**Comment by PlantGirlCodes** [comment]
Interested in the raffle and learning more

**Comment by binford-development** [comment]
greeting = "Hello! :)"
print(greeting)

**Comment by clelange** [comment]
Luck is all you need 😄

**Comment by Praachi12** [comment]
Hello

**Comment by pedrodovale** [comment]
Hi!

**Comment by ghost** [comment]
Can I have a raffle ticket please ?  :)

**Comment by jspoppem** [comment]
Good morning.

**Comment by wposner** [comment]
This is awesome!

**Comment by DarryStonem** [comment]
nice talk! 👍

**Comment by vivekkoya** [comment]
Hello, thank you for this opportunity.

**Comment by jagjitraja** [comment]
Hollla

**Comment by rvadnai** [comment]
Hello from Chicago!

**Comment by vic70** [comment]
great talk!

**Comment by AnthonyByansi** [comment]
Super awesome!

**Comment by LawrenceELee** [comment]
Leaving a comment to enter the raffle.

**Comment by mihovilbraim** [comment]
Hi Andrea!

**Comment by gchundru9** [comment]
Hello

**Comment by shanphd** [comment]
Its Awesome thanks

**Comment by fstevensonv** [comment]
hey

**Comment by itxcrusher** [comment]
Hello, great session!

**Comment by CholongPak** [comment]
Hello

**Comment by AndreaLaruta** [comment]
This is comment! Hello Tocaya(a person with same name)!

**Comment by tayabr** [comment]
hello

**Comment by tomsouza4** [comment]
Tom Souza/ SF Trentino

**Comment by vifeng** [comment]
Hi

**Comment by TomVasile** [comment]
:)

**Comment by Technol0gistE** [comment]
Hi!

**Comment by lcardosobr** [comment]
Hi

**Comment by vishalkr2** [comment]
Hello

**Comment by aruncpt** [comment]
Hello Everyone, Codespaces is awesome

**Comment by mcneilltc** [comment]
Great session!

**Comment by MuhammadUmarAsad** [comment]
Heyo hope I win

**Comment by priku** [comment]
Hello

**Comment by simpleanilcha** [comment]
hi!

**Comment by Oladigbs18** [comment]
I love GitHub Codespace as I have tried using it before. It is more like an an online version of Visual Studio Code

**Comment by vedant-kakde** [comment]
GitHub 🚀

**Comment by SEM-DEV** [comment]
Hello

**Comment by Sakshi-Hardwani** [comment]
Amazing session

**Comment by x4nemi** [comment]
🪅

**Comment by Saba42V** [comment]
Nice session,

**Comment by adityadahake24** [comment]
Amazing Session 🙌👍

**Comment by aruncpt** [comment]
Great session

**Comment by LabminMe** [comment]
Thank you!
This is a great session and an opportunity to connect with the community at large. :-)

**Comment by saivenus** [comment]
THAT WAS A GREAT SESSION 😍

**Comment by mbz4** [comment]
hello world!

**Comment by thermond13** [comment]
Great session.

**Comment by PaulvonBerg** [comment]
<3

**Comment by ilyalehrman** [comment]
Hi all

**Comment by Martokim** [comment]
Holla

**Comment by AshishYesale7** [comment]
Hey !!!

**Comment by cbecerrae** [comment]
Hello!

**Comment by nirupa13** [comment]
Hello!

**Comment by sophipophi** [comment]
hi!!

**Comment by ren276** [comment]
hiii

**Comment by SEM-DEV** [comment]
Hello,

**Comment by tumuhairwe** [comment]
hey ya!

**Comment by abelgamo** [comment]
Hello

**Comment by ubaidullahshuaib** [comment]
hi

**Comment by alejandro-cn-dev** [comment]
Hello 👋

**Comment by DevSamLee** [comment]
HelloHello 🍔

**Comment by hmartinezl** [comment]
thank!

**Comment by Blackx16** [comment]
Konichiwa

**Comment by Raysika** [comment]
Hey everyone, great to be here

**Comment by ruthbacci** [comment]
Hola!

**Comment by MuhammadUmarAsad** [comment]
Can I have a raffle ticket please ? :)

**Comment by LahekarPiyush** [comment]
Hello, here after losing in the Kahoot Quiz :(

**Comment by t-cecilia-nguyen** [comment]
:)

**Comment by Martokim** [comment]
![Screenshot (315)](https://github.com/gittogethers/intro-codespaces/assets/96081023/29cb92ec-0128-412c-8dcf-95eaf3b5fd4a)
:( was not able to even participate in the kahoot :(

**Comment by fadygerman** [comment]
Hi Guys

**Comment by AndreaGriffiths11** [comment]
Thank you so much for participating! 🙏🏽 @DarryStonem, please email me, so I can reply with your prize! andreagriffiths11@github.com
