### ISSUE TITLE
greetings

### ISSUE THREAD

**Issue by Martokim** [gittogethers/intro-codespaces#4]
hello

**Comment by jayinc** [comment]
Hola @AndreaGriffiths11

**Comment by LawrenceELee** [comment]
no, you don't make a new issue. this is the wrong thread...

**Comment by Martokim** [comment]
> no, you don't make a new issue. this is the wrong thread...

oh okay new here thanks

**Comment by fadygerman** [comment]
Hi Everyone

**Comment by AndreaGriffiths11** [comment]
Thanks everyone!

**Comment by riteshzode** [comment]
Hii
